
steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=go-calculator']

  - name: 'gcr.io/cloud-builders/go'
    args: ['test', 'go-calculator']
    env: ['PROJECT_ROOT=go-calculator']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/go-calculator', '.']

images: ['gcr.io/$PROJECT_ID/go-calculator']
